### ISSUE TITLE
Fixed suggestion

### ISSUE THREAD

**Issue by cortesa** [hibiken/react-places-autocomplete#110]
Crate a prop FixedItem that are fixed on top of the suggestion's dropDown, it works like AutocompleteItem but render before suggestions this are defined by user using an array: 

New porp for __`<PlacesAutocomplete/>`__,  __`fixedItems`__ type array

```
const fixtures = [
  {label: 'My position', location: {lat: 53.5459, lng: 9.966576}, className='anything1'},
  {label: 'My house', location: {lat: 53.5495, lng: 9.9625}, className='anything2'},
  {label: 'My Work', location: {lat: 53.5610, lng: 10.0259}, className='anything3'}
];
-------------------------------------------
<PlacesAutocomplete
      inputProps={addrInputProps}
      autocompleteItem={addrAutocompleteItem}
-->   fixedItems = { fixtures }
      onSelect={this.addrHandleSelect}
      onEnterKeyDown={this.addrHandleSelect}
      classNames={cssClasses}
/>
```
__Props of the fixtures objects.__
  label = Text to show in dropdown suggestions list
  location = Coords that define the location
  placeId = ID that define the location
  address = Addres that define the location
  className = CSS class that apply to that suggestion

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
