### ISSUE TITLE
How to include maps.googleapis.com/maps/api/js in component, not in HTML ?

### ISSUE THREAD

**Issue by bogutski** [hibiken/react-places-autocomplete#111]
Hi! What you recommend  to do this?

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>

**Comment by timfisher** [comment]
I used https://www.npmjs.com/package/react-load-script and then initalised the autoloader when the scriptloaded has called

**Comment by skeletorkun** [comment]
it would have been better to be able to pass it as a prop. (e.g. https://www.npmjs.com/package/location-autocomplete)

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
