### ISSUE TITLE
Autocomplete value onchange is ignoring options

### ISSUE THREAD

**Issue by timfisher** [hibiken/react-places-autocomplete#112]
The drop down works with these options:

const options = {
types: ['address'],
componentRestrictions: {country: 'uk'}
} 

However the onChange value from the typed in text remains in the USA until the dropdown is clicked.

**Comment by kenny-hibino** [comment]
@timfisher Thank you for reporting!
 Could you provide more details?

**Comment by timfisher** [comment]
Kenny, please see the video here:

https://sendvid.com/idj0zws3

**Comment by kenny-hibino** [comment]
I see. Would you mind providing me a code snippet for rendering these input fields?

**Comment by timfisher** [comment]
Hi Kenny,

I think the problem is in geocodeByAddress in utils.js, I've had to replace the geocode with:

      geocoder.geocode({'address': address + ', United Kingdom' }, function (results, status) {

The problem is it doesn't match the first result (I would rather it matched), could you help with that?

**Comment by pjho** [comment]
I was just having the same/similar problem. It seems theres no way to pass options to the geocode lookup, so while you can specify `componentRestrictions` for the suggestions it's not passed onto the `geocodeByAddress` util.

If you are not using the to-be-deprecated callback parameter on [geocodeByAddress](https://github.com/kenny-hibino/react-places-autocomplete/blob/master/src/utils.js#L1) then that function is fairly lightweight. The following is that util with callbacks removed and the ability to add config to `geocoder`. You can use this to be able to add your country restriction in `componentRestrictions` when responding to suggestion selection.

```
export const geocodeByAddress = (address, opts = {}) => {
  const geocoder = new google.maps.Geocoder()
  const OK = google.maps.GeocoderStatus.OK

  return new Promise((resolve, reject) => {
    geocoder.geocode({ address, ...opts }, (results, status) => {
      if (status !== OK) {
        reject(status)
      }
      resolve(results)
    })
  })
}

// usage
geocodeByAddress('Wellington', { componentRestrictions: { country: 'NZ' } })
```

@kenny-hibino could be a nice addition when you do deprecate the callback param. Thanks for an awesome library!

**Comment by jinjingbo** [comment]
Hi guys, I am having the same issue here. I need to restrict the dropdown result to AU only. 

@pjho I have tried your post, doesn't seem to be working. The result dropdown list still not filtering by country. 
@kenny-hibino Any advice on how to add the `componentRestrictions` supports?

#114 also want the same thing. 
Thank you all!

**Comment by jinjingbo** [comment]
Actually I found where I went wrong, a silly mistake: I used `ComponentRestrictions` instead of `componentRestrictions`. It is case sensitive. 

Below option setting works with the original function   geocodeByAddress  from the util:
` const options = {
  componentRestrictions: { country: ['AU'] },
  types: ['establishment']
}; `

**Comment by AndreiCalazans** [comment]
prop `searchOptions` wasn't working for me, `options` did.

"react-places-autocomplete": "^6.1.3",


Since they don't keep a changelog idk if this was changed on the newer versions.
