### ISSUE TITLE
Autoselect/Capture specific options from suggestions

### ISSUE THREAD

**Issue by MMachado-uy** [hibiken/react-places-autocomplete#114]
* Scenario: 
    I have an application where you select a city and filter services from there, the `autocompleteItem` is filtered by country (not US).
* Problem:
    If a user sets a value but doesn't select any option from the suggestions, the submission of the form searches for the input everywhere, resulting in finding an undesired location in most cases.
* Solution/Need:
    Some kind of return value for the autocomplete where you can parse the suggestions (a suggestion array, maybe?) to handle those scenarios. Currently I'm taking the _suggestion_ from `autocompleteItem` and checking by hand to filter the first result to autocomplete the input.

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
