### ISSUE TITLE
Component should render suggestions when inputProps.value changes

### ISSUE THREAD

**Issue by DaddyWarbucks** [hibiken/react-places-autocomplete#121]
The component only fetches predictions when a change happens on the internal input element's `onChange` method. This means that if an external source changes `inputProps.value`, the component does not render the suggestions list.

I want to use my own input component (specifically the MUI `<Field />`). I saw where this was removed from a previous version that allowed you to add children to the component for simplification of the library, which makes sense.

I have wrapped my `<Field>` and `<PlacesAutocomplete>` components in a container that ties the value/inputProps.value of each component to the same state. My plan is/was to simply hide the PlacesAutocomplete's input element via CSS. Then I would have a custom input element and PlacesAutocomplete offers ample customization of the `<AutocompleteItem/>` to be placed under my custom input.

But, because  PlacesAutocomplete only calls `fetchPredictions` on the internal element change, it is not called when a new `inputProps.value` is supplied and therefore does not work for what I am trying to do.

Perhaps the component could call `fetchPredictions` on `componentWillReceiveProps`?
```
componentWillReceiveProps(nextProps) {
  if (nextProps.inputProps.value !== this.props.inputProps.value) {
    this.fetchPredictions(nextProps.inputProps.value)
  }
}

...

fetchPredictions(_value) {
    const value = _value ?  _value : this.props.inputProps.value
    if (value.length) {
      this.autocompleteService.getPlacePredictions({
        ...this.props.options,
        input: value
      }, this.autocompleteCallback)
    }
  }

```

Note the small change to `fetchPredictions` which now takes in a `_value` and either uses that or props.

I think this would give the component more flexibility (giving a way to use a custom input component) without complicating the library too much.

**Comment by kenny-hibino** [comment]
@DaddyWarbucks Sounds like a good idea! PR is welcome!

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
