### ISSUE TITLE
Force autocomplete dropdown open

### ISSUE THREAD

**Issue by johnbrett** [hibiken/react-places-autocomplete#126]
Hi, great work on this works pretty effortlessly out of the box.

Is there a way to keep the autocomplete tray open? I have some styling issues I'm trying to debug, but finding it quite difficult to figure out a way to keep the dropdown box open while I fix them.

**Comment by kenny-hibino** [comment]
Thank you for opening this issue @johnbrett! 
I can see your paint point, I have experienced similar issues with other react component libraries. 

This will be a good enhancement for a better developer experience. I'm thinking something like `alwaysRenderSuggestion` boolean prop might be useful. (`react-autosuggest` has this prop).
But this might require the user of the library to provide default suggestion items.

Another solution I can think of is to add a prop to enable easy debugging in dev environment. 
I need to investigate how to go about doing that.
Let me know if you have an idea, and PR is always welcome!

**Comment by johnbrett** [comment]
`alwaysRenderSuggestion` with some default suggestion items would be perfect, as would a prop for easy debugging. Anything really, whichever is easiest to implement :D Ok will see if I can put a PR together for this.

Thanks for the quick reply also!

**Comment by andrefox333** [comment]
For anyone in the future running into the same problem, I simply right click and inspect the suggestion element and that forces the autocomplete tray component to stay open.

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
