### ISSUE TITLE
Anyone have experience with using this in conjunction with react-google-maps?

### ISSUE THREAD

**Issue by JarLowrey** [hibiken/react-places-autocomplete#131]
And the subsequent load order issues that arise?  https://stackoverflow.com/questions/46780770/utilizing-google-maps-in-other-components-through-withscriptjs-withgooglemap

Basically I don't want to have a script tag in my HTML header (`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>`) but would prefer to load it in asynchronously in my components via JS.

**Comment by stevokk** [comment]
Wrap the common parent of the two components with the withJS() HOC ?

**Comment by jencarlile** [comment]
I know this issue is a few months old, but I was wondering if you arrived at a solution? I am running into the same thing.  Thanks.
