### ISSUE TITLE
Since update to react 16, I have an error 

### ISSUE THREAD

**Issue by Steffi3rd** [hibiken/react-places-autocomplete#152]
Warning: Failed prop type: Cannot read property 'hasOwnProperty' of undefined

How to fix that please?

**Comment by Huanzhang89** [comment]
Might be a good idea to post the code for your implementation. I also had this error but it was due to bad implementation.

**Comment by wengjincheng** [comment]
I have this error too. I'm following get start and get this error. Is the docs wrong?

**Comment by lc3t35** [comment]
There are 3 "hasOwnProperty" in code (https://github.com/hibiken/react-places-autocomplete/search?q=hasOwnProperty&type=Code), none of them checks if object exists before calling hasOwnProperty

**Comment by sambokai** [comment]
Is this still causing issues?

**Comment by lc3t35** [comment]
Why not fix simply fix this 3 lines of code ? as you're using lodash, just replace by _.has(obj, property) to check if property exists ?

**Comment by sambokai** [comment]
Fair enough. I just glanced over this while cleaning up the repo issues and wasn't sure if this was fixed. I'll quickly create a PR.

**Comment by sambokai** [comment]
However, the two cases in this function seem fine, as the `options` object defaults to `{}` and therefore always exists when `hasOwnProperty` is invoked. https://github.com/hibiken/react-places-autocomplete/blob/9b1e093e742f0259cdced43663ba1164b7eef52d/src/PlacesAutocomplete.js#L257

I'll handle the remaining case with a simple `obj &&`. Not a fan of using lodash for something like this.

**Comment by sambokai** [comment]
Change was merged. Hope this is fixed. Thanks everyone
