### ISSUE TITLE
Getting Airport Data

### ISSUE THREAD

**Issue by luthfirrahmanb** [hibiken/react-places-autocomplete#167]
Hi, Thanks for awesome library, and i have a question, how to just getting airport data? Thank You

**Comment by CoVoCre** [comment]
Hey ! What do you mean @luthfirrahmanb by just Airport Data ?
Do you want to restrict autocomplete results to only airport related results across the world ? How do you define if it is "Airport data"? 
Maybe if you just want results that have to do with one airport, just use the options prop as described in the readme : https://github.com/kenny-hibino/react-places-autocomplete#options 
You'll see how you can "bias" with the location, radius etc to in effect restrict the results to a specific area, which could be your airport !

**Comment by CoVoCre** [comment]
I found this from google places api documentation : https://developers.google.com/places/supported_types#table1

It seems the really precise type "airport" for getting only airport places, is "only for [searches](https://developers.google.com/places/web-service/search) and when [adding](https://developers.google.com/places/web-service/add-place) a place.

**Comment by Dashue** [comment]
I'm trying the type 'establishments' which should be supported. But no matter how I try to specify it to  searchOptions it doesn't reflect in the queried url? Had any success with this?

types: ['establishment']
types: 'establishment'
type ['establishment']
type: establishment
