### ISSUE TITLE
How get address by lat long?

### ISSUE THREAD

**Issue by safeimuslim** [hibiken/react-places-autocomplete#180]
How get address by lat long?

**Comment by safeimuslim** [comment]
fixed by use reverse geocoding package

**Comment by efstathiosntonas** [comment]
@safeimuslim can you share  your code on how to do this?

**Comment by ashishlal91** [comment]
Where is the solution @safeimuslim

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
