### ISSUE TITLE
the google request is made wit the sugestion but suggestion is not shown on field on mouse click

### ISSUE THREAD

**Issue by pulkitgpt27** [hibiken/react-places-autocomplete#227]
**Do you want to request a *feature* or report a *bug*?**bug

**What is the current behavior?**text is not shown on the textField when i click on any suggestion

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**just type in textfield and click on any suggestion

**What is the expected behavior?**suggestion should be shown on textField

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**google chrome ,ubuntu 16.04,placesAutocomplete version 7.1.1

**Comment by CoVoCre** [comment]
Hey !
What do you mean by the request is made ?
And what do you mean by not shown on field on mouse click ?

If you mean that as you type, you get the suggestions you want, but when you click on one, the text of the suggestion doesn't show in the input field, maybe you forgot to implement a [onSelect](https://github.com/hibiken/react-places-autocomplete/blob/master/README.md#onSelect) function ?

**Comment by pulkitgpt27** [comment]
yes exactly this but i have implemented onselect method also

**Comment by pulkitgpt27** [comment]
i get the value which i want but text doesnt show on field 
when i select suggestion using enter key then shown on textField

**Comment by CoVoCre** [comment]
@pulkitgpt27 in you onSelect method, you need to change the value, just like onChange if you want the displayed value to change in the input field ;) 
Maybe like : 
```js
onSelect = (value) => {
    onChange(value);
    //...and the rest of your stuff for onSelect here !
}
```
If you still have problems, maybe show us some code ?

**Comment by pulkitgpt27** [comment]
thanx man it worked but i cant understand why

**Comment by CoVoCre** [comment]
I find it weird too, if when you pressed the keyboard key enter it changed the text in the input field (calling onChange), but when you clicked on a suggestion it didn't... Is this what was happening ?
If you never had the text show up in the input field, it is normal because onSelect doesn't call onChange, if you want to have it that way you have to implement it like above ;)

**Comment by pulkitgpt27** [comment]
hey can you guide me how to restrict suggestions to show only city state country instead of regular suggestions

**Comment by CoVoCre** [comment]
Hey @pulkitgpt27 , you can see what is possible in the [searchOptions section of the README](https://github.com/hibiken/react-places-autocomplete#searchOptions). What is possible or not for your specific request come down from the [maps api place types list](https://developers.google.com/places/supported_types#table3) !
I don't know what you mean "by city state country", but if you mean capital I haven't seen a way to do this ! You could try `(cities)`, `sublocality_level_1` or `sublocality_level_2` but I don't exactly know what you'd get. Have a look at the Address Types and Address Component Types section of the [geocoding docs](https://developers.google.com/maps/documentation/geocoding/intro).

**Comment by pulkitgpt27** [comment]
thanks for your constant support
