### ISSUE TITLE
this.props.children is not a function

### ISSUE THREAD

**Issue by The-Code-Monkey** [hibiken/react-places-autocomplete#230]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
crashes on load with title as error
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it should load
**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
latest version of react places auto complete and chrome and macosx

**Comment by CoVoCre** [comment]
I think it'd help if you gave us some code 😅😅😅😄

**Comment by The-Code-Monkey** [comment]
```
const inputProps = {
      value: this.state.address,
      onChange: this.onChange,
      placeholder: this.props.placeholder
    };

    const renderSuggestion = ({ suggestion }) => (
      <div className="address-result">
        <i className="fa fa-map-marker" />
        {suggestion}
      </div>
    );

    const renderFooter = () => (
      <div className="dropdown-footer">
        <div>
          <img src={GoogleLogo} alt="" />
        </div>
      </div>
    );


const cssClasses = {
      input: "form-control",
      autocompleteContainer: "address-result-container",
      root: "address-wrapper"
    };


return (
<PlacesAutocomplete
          inputProps={inputProps}
          classNames={cssClasses}
          renderSuggestion={renderSuggestion}
          onSelect={this.handleSelect}
          renderFooter={renderFooter}
        />
)



```

And the thing that is breaking is in a version above 6.1.3.

this.props.children is breaking inside of the react-places-autocomplete package itself im not the one calling it

**Comment by CoVoCre** [comment]
Well, I think you have to read the Readme of the new versions 😉 The component now requires a (child function)[https://github.com/hibiken/react-places-autocomplete/blob/master/README.md#children] to be passed, which will render the suggestions. Check it out, it's quite clever !

**Comment by The-Code-Monkey** [comment]
ah ok I didn't see that maybe there should be an example at the top of the doc so that you don't have to trawl through all the code looking for a major change like that

**Comment by CoVoCre** [comment]
A changelog would be great, I agree ! 😁
But the simplr example is right at the top of the Readme, isn't it ?
