### ISSUE TITLE
option to not clear suggestions on blur

### ISSUE THREAD

**Issue by jedwards1211** [hibiken/react-places-autocomplete#233]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Whenever I blur the input, react-places-autocomplete clears the suggestions, so when I focus the input again, no suggestions come up.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
If I refocus the input, it shows the same suggestions as before.  Or at least I can pass an option to make it do that.

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
The latest version as of today, not browser/OS specific

**Comment by jedwards1211** [comment]
Oh I guess the point of this is that the dropdown should be visible only if there are selections.  I had been trying, mistakenly, to combine this with `react-select`, but `react-select` is being really buggy so I'm going to use this by itself :)

**Comment by akinnee** [comment]
I had to disable blur so I could tweak the CSS in the inspector without the suggestions disappearing on me. Here's a temporary solution if anyone else needs to do that:
```
<PlacesAutocomplete ref={(c) => {
          if (!c) return;
          c.handleInputOnBlur = () => {};
}} />
```
