### ISSUE TITLE
couldn't get it works with formik 

### ISSUE THREAD

**Issue by elzayat** [hibiken/react-places-autocomplete#244]

**Comment by madeinspace** [comment]
it is working with formik

**Comment by Kukunin** [comment]
The problem is that `<input onChange={handleChange} />` fires `handleChange` with an event, while `<PlacesAutocomplete onChange={handleChange} />` fires with a value. so Formik can't use it as a callback

**Comment by Kukunin** [comment]
works with formik's `setFieldValue`: `<PlacesAutocomplete onChange={(value) => setFieldValue('city', value)} />`

**Comment by abhilashrathod** [comment]
> works with formik's `setFieldValue`: `<PlacesAutocomplete onChange={(value) => setFieldValue('city', value)} />`

Thank you for your reply! But; it is still not working for me

**Comment by elzayat** [comment]
It Works for me 

<Formik
  initialValues={{
    pickup: ""
  }}
  onSubmit={(values, actions) => {
    this.props.getpricelist(values);
  }}
  validate={validate}
  render={({ handleSubmit, setFieldValue, values, errors, touched }) => (
    <form onSubmit={handleSubmit}>
      <Field
        name="pickup"
        type="pickup"
        value={values.pickup}
        render={({ field, form }) => {
          return (
            <Autocomplete
              {...form}
              {...field}
              icon="green"
              placeholder="Enter pickup location"
              label="LOCATION (PICK-UP)"
              onChange={e => {
                form.setFieldValue("pickup", e);
              }}
            />
          );
        }}
      />
    </form>
  )}
/>;

**Comment by griffith-icp** [comment]
Hey @Kukunin , is there a way we can get it to fire both an event and the value?
Because I'm trying to integrate it with formik and I'm facing the same problems as @abhilashrathod .
I'm guessing I'll have to clone the repo and modify the way events are handled myself.

**Comment by vitorzerbeto** [comment]
The secret to use with Formik is the `setFieldValue` function.

Into the `onChange` method, of the `<PlacesAutocomplete />` component, you'll need to call `setFieldValue` to update the formik input value.

This function come from the `render({ setFieldValue })` method, provide by the `<Formik />` component.

https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean-void

On my case, i'm using the autocomplete inside of a `<Field />` component. That has  `{field, form}` coming from his `render` function.
The `form` prop contains the `setFieldValue` function. Than i pass to the autocomplete.

Something like that:

```
handleChange({ name, form, search }) {
   form.setFieldValue(name, search);
}

renderPlacesAutocomplete({ field, form }) {

    return (
      <PlacesAutocomplete
        value={field.value}
        onChange={search => {
          this.handleChange({ name: field.name, form, search });
        }}
      >
        {({ getInputProps, getSuggestionItemProps, suggestions }) => {
          const additionalProps = {
            name: field.name,
            className: 'form-input__field',
          };

          const autocompleteInputProps = getInputProps(additionalProps);

          return (
            <div className="autocomplete-root">
              <input {...autocompleteInputProps} />
              <div className="autocomplete-dropdown-container">
                {suggestions.map(suggestion => (
                  <div {...getSuggestionItemProps(suggestion)}>
                    <span>{suggestion.description}</span>
                  </div>
                ))}
              </div>
            </div>
          );
        }}
      </PlacesAutocomplete>
    );
}

render() {
    <Field
        name={name}
        handleBlur={onBlur}
        {...inputProps}
        render={({ field, form }) => this.renderPlacesAutocomplete({ field, form })}
    />
}
```

**Comment by RemyMachado** [comment]
If you are using `useField()` or `<Field />` as a children of `PlacesAutocomplete` and you need the `field`/`meta` to be available in the `parent Component`, you can use a second `<Field />` with the same `name` prop to pass them down, see example:

With `<Field />`
```javascript
<Field name="same-name"> // they got the same name
	{({ field, meta }) => (
		<div>
			<PlacesAutocomplete
				value={field.value}
				// ...
			>
				<CustomInput name="same-name" /> // they got the same name
			</PlacesAutocomplete>
		</div>
	)}
</Field>	
```
or

With `useField()`
```javascript
const [field, meta] = useField("same-name); // they got the same name

return (
	<div>
		<PlacesAutocomplete
			value={field.value}
			// ...
		>
			<CustomInput name="same-name" /> // they got the same name
		</PlacesAutocomplete>
	</div>
)
```

Hope it helps.
