### ISSUE TITLE
Using google maps api as npm

### ISSUE THREAD

**Issue by g-borgulya** [hibiken/react-places-autocomplete#245]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Seemingly the only way to use this package is to load google maps api as a script.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is a problem for several reasons, to put it simply this is not the modern approach.

**What is the expected behavior?**
Have the option to use the official google maps api as an npm.
I see two options:
- `@google/maps` could be an optional peer dependency of this package, and react-places-autocomplete could try using it with the google api key provided as a prop to the PlacesAutocomplete component.
- instead of only depending on `window.google` PlacesAutocomplete could have google as an optional prop, where google api instance could be passed that was instantiated somewhere in the code.

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
all

**Comment by sambokai** [comment]
[@google/maps has been deprecated](https://www.npmjs.com/package/@google/maps) and is replaced by [@googlemaps/google-maps-services-js](https://www.npmjs.com/package/@googlemaps/google-maps-services-js), which doesn't seem to include any autocomplete feature.

This request seems impossible as of today, so i suggest this is closed.
