### ISSUE TITLE
TypeScript definitions are outdated

### ISSUE THREAD

**Issue by ThomWright** [hibiken/react-places-autocomplete#246]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

V6 of `react-places-autocomplete`  and `@types/react-places-autocomplete` work together, but `@types/react-places-autocomplete` v7 hasn't been updated/released.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Install latest versions of each, and copy the example from the readme.

**What is the expected behavior?**

No compile errors

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

Version 7+

**Comment by hibiken** [comment]
Hey Thom,

thank you for reporting this. Would you mind reporting this issue in https://github.com/DefinitelyTyped/DefinitelyTyped/ repo?

**Comment by ApeNox** [comment]
i have updated the types by myself, they have updated it in master.

**Comment by tkrotoff** [comment]
Types are now up to date, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/90961b6110f9848311859f25b600d9e25e9bd783/types/react-places-autocomplete/index.d.ts
This issue can be closed
