### ISSUE TITLE
How to get address detail when selected address: state, region, street, router. city ....

### ISSUE THREAD

**Issue by 0xngoubou** [hibiken/react-places-autocomplete#252]
I need location detail from selected address.
Thanks.
For ex:
![screen shot 2019-01-18 at 4 59 12 pm](https://user-images.githubusercontent.com/4811620/51379608-6e125f00-1b42-11e9-9eec-e99523016ae5.png)

**Comment by city41** [comment]
This component does not appear to do this. In order to get the details, you need to use the `placeId` you got back from this component and then make a details request

here is some very raw code where I just got this working

```
import React from 'react';
// import classnames from 'classnames';
import PlacesAutocomplete from 'react-places-autocomplete';

interface ILocationDropdownProps {
    className?: string;
    //tslint:disable-next-line:no-any
    onLocationChosen: (error: Error | null, result: any) => void;
}

interface ILocationDropdownState {
    //tslint:disable-next-line:no-any
    address: any;
}

async function getDetailsForPlaceId(placeId: string) {
    //tslint:disable-next-line:no-any
    return new Promise((resolve: any, reject: any) => {
        // @ts-ignore
        const placesService = new google.maps.places.PlacesService(document.createElement('div'));
        const request = {
            placeId,
            fields: ['address_components']
        };
        placesService.getDetails(request, (result: unknown, status: unknown) => {
            // address details are here
        });
    });
}

class LocationDropdown extends React.Component<ILocationDropdownProps, ILocationDropdownState> {
    state: ILocationDropdownState = {
        address: ''
    };

    handleChange = (address: string) => {
        this.setState({
            address
        });
    };

    handleSelect = async (address: string, placeId: string) => {
        const details = await getDetailsForPlaceId(placeId);
        this.props.onLocationChosen(null, details);
    };

    render() {
        // const { className } = this.props;

        // const classes = classnames('locationDropdown', className);
        return (
            <PlacesAutocomplete
                value={this.state.address}
                onChange={this.handleChange}
                onSelect={this.handleSelect}
                searchOptions={{
                    types: ['address']
                }}
            >
                {({ getInputProps, suggestions, getSuggestionItemProps, loading }) => (
                    <div>
                        <input
                            {...getInputProps({
                                placeholder: 'Search Places ...',
                                className: 'location-search-input',
                                'aria-activedescendant': ''
                            })}
                        />
                        <div className="autocomplete-dropdown-container">
                            {loading && <div>Loading...</div>}
                            {suggestions.map(suggestion => {
                                const className = suggestion.active
                                    ? 'suggestion-item--active'
                                    : 'suggestion-item';
                                // inline style for demonstration purpose
                                const style = suggestion.active
                                    ? { backgroundColor: '#fafafa', cursor: 'pointer' }
                                    : { backgroundColor: '#ffffff', cursor: 'pointer' };
                                return (
                                    //@ts-ignore
                                    <div
                                        key="1"
                                        {...getSuggestionItemProps(suggestion, {
                                            className,
                                            style
                                        })}
                                    >
                                        <span>{suggestion.description}</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}
            </PlacesAutocomplete>
        );
    }
}

export default LocationDropdown;
```

**Comment by maximeBAP** [comment]
I've done it like this if it could help
`import React from 'react';
import PlacesAutocomplete, {
    geocodeByAddress,
    getLatLng,
} from 'react-places-autocomplete';
import { Field } from 'redux-form';

const searchOptions = {
    componentRestrictions: {country: 'fr'},
    type: ['address']
}

export default class LocationSearchInput extends React.Component {
    constructor(props) {
        super(props);
        this.state = { address: '' };
        this.addressForm = {
            address: '',
            street_number: React.createRef(),
            route: React.createRef(),
            locality: React.createRef(),
            administrative_area_level_2: React.createRef(),
            administrative_area_level_1: React.createRef(),
            country: React.createRef(),
            postal_code: React.createRef(),
            lat: React.createRef(),
            lng: React.createRef()
        }
    }

    handleChange = (address) => {
        this.setState({ address });
    };

    handleSelect = address => {
        geocodeByAddress(address)
        .then(results => {
            for (let i = 0; i < results[0].address_components.length; i++) {
                const addressType = results[0].address_components[i].types[0];
                if (this.addressForm[addressType]) {
                    this.addressForm[addressType].current.value = results[0].address_components[i].long_name;
                }
            }
            getLatLng(results[0])
            .then(latLng => {
                this.addressForm.lat.current.value = latLng.lat;
                this.addressForm.lng.current.value = latLng.lng;
            });
        })
        .catch(error => console.error('Error', error));
        this.addressForm.address = address;
    };

    render() {
        return (
        <PlacesAutocomplete
            value={this.state.address}
            onChange={this.handleChange}
            onSelect={this.handleSelect}
            searchOptions={searchOptions}
        >
            {({ getInputProps, suggestions, getSuggestionItemProps, loading }) => (
            <div>
                <Field
                    {...getInputProps({
                        name: "address",
                        placeholder: "Adresse",
                        className: "location-search-input"
                    })}
                    component="input"
                    required
                />
                <div className="autocomplete-dropdown-container">
                {loading && <div>Loading...</div>}
                {suggestions.map(suggestion => {
                    const className = suggestion.active
                    ? 'suggestion-item--active'
                    : 'suggestion-item';
                    return (
                    <div
                        {...getSuggestionItemProps(suggestion, {
                        className,
                        })}
                    >
                        <span>{suggestion.description}</span>
                    </div>
                    );
                })}
                </div>
                <input name="number" id="number" placeholder="number" ref={this.addressForm.street_number} />
                <input name="street" id="street" placeholder="street" ref={this.addressForm.route} />
                <input name="zipCode" id="zipCode" placeholder="zipCode" ref={this.addressForm.postal_code} />
                <input name="city" id="city" placeholder="city" ref={this.addressForm.locality} />
                <input name="department" id="department" placeholder="department" ref={this.addressForm.administrative_area_level_2} />
                <input name="region" id="region" placeholder="region" ref={this.addressForm.administrative_area_level_1} />
                <input name="country" id="country" placeholder="country" ref={this.addressForm.country} />
                <input name="latitude" id="latitude" placeholder="latitude" ref={this.addressForm.lat} />
                <input name="longitude" id="longitude" placeholder="longitude" ref={this.addressForm.lng} />
            </div>
            )}
        </PlacesAutocomplete>
        );
    }
}`

**Comment by eleventhaus** [comment]
If you're getting the error that 'google' is undefined, switch it out for `window['google']` instead
