### ISSUE TITLE
onBlur event handler

### ISSUE THREAD

**Issue by MichaelVoloshyn** [hibiken/react-places-autocomplete#259]
*feature*

It would be great if you add onBlur event handler.
It could help in situation, when user clear the field and we can render the old value from redux store when focus is out of field.

**Comment by hibiken** [comment]
You should be able to pass it as a part of argument to `getInputProps`.

This function will return the props that you can spread over the <input /> element. You can optionally call the function with an object to pass other props to the input.

```jsx
<input
  {...getInputProps({
     placeholder: 'Search Places ...',
     className: 'location-search-input',
     onBlur: () => { /* your blur event hander logic */},
   })}
/>
```
