### ISSUE TITLE
Sample site and component in general not working...anyone else having this issue?

### ISSUE THREAD

**Issue by carolinecreid** [hibiken/react-places-autocomplete#267]
Tried implementing the newest version as well and is still broken. I'm assuming it's a bigger issue than just our code since the sample site is also not working? Thanks!

**Comment by cesarvarela** [comment]
Have you changed the api key? The sample site doesn't work because it exceeded the query limit

**Comment by hibiken** [comment]
The demo is currently not working since I'm on free tire and exceeding query limit 😸
