### ISSUE TITLE
Set the data fields to return when the user selects a place.

### ISSUE THREAD

**Issue by dinorhythms** [hibiken/react-places-autocomplete#271]
Please how can i set fields to avoid paying for data that i don't need by restricting the set of
place fields that are returned.

 autocomplete.setFields(['address_component']);

Thanks

**Comment by sugarp** [comment]
Im missing this feature as well....

**Comment by sambokai** [comment]
`setFields` is a function of the `Autocomplete` class, which does a subsequent place detail request on its own. 

This library uses the `Autocomplete Service` which doesn't do a place details request, but lets the users do it themselves. You would get the `placeId` from `onSelect()` and manually do a places details request with that. It's only there where you specify which fields you want returned. 

So this request is out of scope of this project.

From https://developers.google.com/maps/documentation/javascript/reference/places-widget#Autocomplete:

> Sets the fields to be included for the Place in the details response when the details are successfully retrieved. For a list of fields see PlaceResult.
