### ISSUE TITLE
geocodeByAddress returns "Raas Chaabad, Somalia" when searching for "Somalia"

### ISSUE THREAD

**Issue by CodeForcer** [hibiken/react-places-autocomplete#282]
When searching into geocodeByAddress with the name "Somalia" the formatted address return refers to an isolated city off the coast of Somalia called Raas Chaabad

**Comment by sambokai** [comment]
Please use the discussion board https://gitter.im/react-places-autocomplete for usage questions. This doesn't seem to be a problem with the library.
