### ISSUE TITLE
do we support "address_components"?

### ISSUE THREAD

**Issue by dbsquared** [hibiken/react-places-autocomplete#287]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
address is returned as a single string, not breaking down to components, e.g. street, city, etc

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
See https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult.address_components

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

**Comment by anthonyko** [comment]
You should be able to get the `address_components` by using the `geocodeByAddress` utility function.

`  handleSelect = address => {
    geocodeByAddress(address)
      .then(results => console.log(results))
      .catch(error => console.error("Error", error));
  };`

**Comment by piyush96arora1** [comment]
Hey, how do we get actual name of palce, what we select from dropdown is the name and address, and in query response, there is not the feild name.? Have any idea? About this?

**Comment by amitcr** [comment]
> You should be able to get the `address_components` by using the `geocodeByAddress` utility function.
> 
> ```
>   handleSelect = address => {
>     geocodeByAddress(address)
>       .then(results => console.log(results[0].address_components))
>       .catch(error => console.error("Error", error));
>   };
> ```

Thank you So much. 

It saved a lot of my time :)

**Comment by tarun-nagpal-github** [comment]
> You should be able to get the `address_components` by using the `geocodeByAddress` utility function.
> 
> ```
>   handleSelect = address => {
>     geocodeByAddress(address)
>       .then(results => console.log(results[0].address_components))
>       .catch(error => console.error("Error", error));
>   };
> ```

@anthonyko Thank you so much for this code.

It saved a lot of my time :)

**Comment by gabe2code** [comment]
> You should be able to get the `address_components` by using the `geocodeByAddress` utility function.
> 
> ```
>   handleSelect = address => {
>     geocodeByAddress(address)
>       .then(results => console.log(results[0].address_components))
>       .catch(error => console.error("Error", error));
>   };
> ```

I'm using the same procedure and I'm receiving a deny access from Google API, I don't want to show any map, just obtain the details of the current suggestion... any suggestion??

`Geocoding Service: This API project is not authorized to use this API.  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

Just for the record, I do have a key, otherwise, I wouldn't able to see the suggestions of Google :(

**Comment by kidoun** [comment]
you should activate  Geocoding Service from your account GCP google

**Comment by gabe2code** [comment]
> you should activate Geocoding Service from your account GCP google

Thanks for the quick response buddy, I'm migrating my app from angular JS to React, and I'm using the same code which works like a charm in angularJS, so, I don't understand why the answer is different here. Even I'm using the `geocodeByPlaceId` onSelect, so :confused:

**Comment by 3skr0** [comment]
It sounds like using  2 api (twice costs) while it can be done only by 1. In the official google example, they are using only google place API:
[places-autocomplete-addressform](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)
