### ISSUE TITLE
Add language in parameters

### ISSUE THREAD

**Issue by arnaudcosson** [hibiken/react-places-autocomplete#291]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Can't request API in a specific language
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Be able to add Optional parameter "language" to API call so the results can be in the user language 
https://developers.google.com/places/web-service/search

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
^7.2.1

**Comment by RobbyUitbeijerse** [comment]
@arnaudcosson what blocks you from using the actual language parameter inside of the script tag? The documentation you referred wants you to add it like this;

`<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&language=nl"></script>`

The results will come in in the specified language via this paramater, as react-places-autocompleted uses the google API's that get loaded via the script

Hope this helps
