### ISSUE TITLE
How can I get placeDetails with the address response in onSelect() callback?

### ISSUE THREAD

**Issue by wiadev** [hibiken/react-places-autocomplete#294]
Hi

Right now, in onChange, onSelect() callbacks, I'm simply getting the address as string but I need to get place details.

https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/places-autocomplete-hotelsearch

I've checked the google-autocomplete documetation and they were calling `autocomplete.getPlace` in onPlaceChange() callback which is calling GoogleService's PlaceDetails api.

How can I do this in this component?

Thanks

**Comment by jomo24** [comment]
@wiadev see this https://github.com/hibiken/react-places-autocomplete/issues/287#issuecomment-534859086

**Comment by sambokai** [comment]
The second argument of `onSelect` is the `placeId`. With that you can do a Place Details API request.

**Comment by import-yuv** [comment]
Hi ,
For getting place details, you need first place id.
Once you get the place id then by using following method you can get the place details.

I have used like this:

const handleAutoCompletePlaceSelected = (placeId:any,addressData:{}) => {
    if (window.google) {
        const PlacesService = new window.google.maps.places.PlacesService(
            predictionsRef.current
        );
        try {
            PlacesService.getDetails(
                {
                    placeId,
                    fields: [
                        "address_components",
                        "name",
                        "business_status",
                        "opening_hours",
                        "formatted_phone_number",
                        "international_phone_number",
                    ],
                },
                place => {
                    const finalData = { ...addressData ,...place};
                    console.log(finalData);   // HERE YOU GET THE COMPLETE PLACE DETAILS
            }
            );
        } catch (e) {
            console.error(e);
        }
    }
};


NOTE:
Here "addressData" is the results from onSelect function.
