### ISSUE TITLE
How to get the value of PlacesAutoComplete in different form/component?

### ISSUE THREAD

**Issue by tillmusshoff** [hibiken/react-places-autocomplete#295]
Hey, I can't figure out how to extract the value of the input field in another component. I have been trying for hours. This is probably a quiet trivial problem, but im still new to react and can't get it to work.

**This is the Places implementation:**
<img width="509" alt="Bildschirmfoto 2019-11-22 um 09 31 25" src="https://user-images.githubusercontent.com/53266983/69411096-904dae00-0d0c-11ea-94fa-6f117942d9bb.png">

**These are my imports and functions within the component I want to access the value from:**
<img width="415" alt="Bildschirmfoto 2019-11-22 um 09 31 52" src="https://user-images.githubusercontent.com/53266983/69411112-9774bc00-0d0c-11ea-85f4-e5b46e9309b7.png">

**And here I insert the Places-component within a form that should be submitted.** Whatever I do, the "city"-field remains empty and should be filled with the places value instead:
<img width="366" alt="Bildschirmfoto 2019-11-22 um 09 32 17" src="https://user-images.githubusercontent.com/53266983/69411122-9c397000-0d0c-11ea-9015-9c1ddd1ee8fd.png">

**Thanks in advance!**

**Comment by sambokai** [comment]
Please use https://gitter.im/react-places-autocomplete for usage questions
