### ISSUE TITLE
Wrong Results getting for one particular address using Geocodebyaddress method.

### ISSUE THREAD

**Issue by Subramani058** [hibiken/react-places-autocomplete#297]
Hi,
I got the issue like getting wrong result from geocodebyaddress method while searching for one particular address.

I searching for **Mylapore** , but it getting results like **1760,Prairie City Road,Folsom,California,United States,95630**.

React Version: 16.3.1,
react-places-autocomplete: 5.4.3

**Comment by sambokai** [comment]
I get the same result in the official example: https://developers.google.com/maps/documentation/geocoding/intro

<img width="978" alt="Screenshot 2020-05-17 at 12 32 13" src="https://user-images.githubusercontent.com/7689616/82142137-782d9600-983a-11ea-88bc-8f5c1da56893.png">

Try a more precise query.

**Comment by kfragkedaki** [comment]
Hello, I have the same issue. However, Google's official results are correct based on the [website](https://developers.google.com/maps/documentation/geocoding/overview) above.

More specifically, when I type "Elpedison Power S.A. Thessaloniki CCPP, Veria, Greece", your library returns (40.6400629, 22.9444191), while Google returns (40.687244, 22.88524) which is the correct one.

<img width="758" alt="Screenshot 2020-08-24 at 6 56 23 PM" src="https://user-images.githubusercontent.com/22832612/91067741-f79de300-e63b-11ea-9c67-2c50d152c838.png">
