### ISSUE TITLE
how get more than 5 cities? 

### ISSUE THREAD

**Issue by knour89** [hibiken/react-places-autocomplete#298]
hello, this is the first time to use react places autocomplete,

I need to increase number of results instead of 5 to be 10, but I don't know how!!!

**Comment by gonzadk** [comment]
it's a little late for you, but probably other people with the same problem could help mine..

short answer: No
long one: this library consumes a google places service to get the suggestions and the google API used for that limits the responses to 5.. you can read more here -> https://developers.google.com/places/web-service/autocomplete#place_autocomplete_responses
