### ISSUE TITLE
Feature Reuest / Bug: Attribution and note on Place API policies

### ISSUE THREAD

**Issue by getorca** [hibiken/react-places-autocomplete#302]
Current Behaviour
Currently the drop-down doesn't contain attribution for google which can result in `RefererDeniedMapError` and the API will not work. I just experienced this and am currently having to have my application reviewed by google for non compliance.

Expected:
At the bottom of the drop-down include the google attribution tag outlined on the places api requirements, https://developers.google.com/places/web-service/policies.

Also suggest a note in the readme referring to user to make sure their website is in compliance with https://developers.google.com/places/web-service/policies

**Comment by sambokai** [comment]
This library wraps the data part of the autocomplete API and provides an interface to build your own UI on top of it **yourself**. We don't provide any opinion on how to design the dropdown or any other part of the UI.
