### ISSUE TITLE
Address and Cities

### ISSUE THREAD

**Issue by developdeez** [hibiken/react-places-autocomplete#304]
I would like to use searchOptions.types to have both address and (cities).
Seems to not work as expected

**Comment by fgobin** [comment]
I'm having a same issue with only (cities). It returns all the addresses regardless if it is a city or airport for example. Did you maybe find a solution in the meantime?

**Comment by developdeez** [comment]
Nope

**Comment by iamvishalbisht** [comment]
bumping this up. Same issue

**Comment by himat** [comment]
Same issue, it's returning all addresses when using just (cities)

**Comment by sambokai** [comment]
I've answered this in this issue: https://github.com/hibiken/react-places-autocomplete/issues/312#issuecomment-629774237
