### ISSUE TITLE
Include postal_code too

### ISSUE THREAD

**Issue by lalspicesresearch** [hibiken/react-places-autocomplete#307]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Returns address without postal_code
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Enter address in autocomplete field, does not return postal_code value along with the full address
**What is the expected behavior?**
Should  return the the address_components field for the place so additional values can be extracted.
**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
^7.2.1

**Comment by sambokai** [comment]
Postal code is not included in a `AutocompletionPrediction`. You need to call the Place Details API for that. https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletePrediction
