### ISSUE TITLE
How to remove country name from search suggestions?

### ISSUE THREAD

**Issue by himat** [hibiken/react-places-autocomplete#309]
I was able to remove the country name via string manipulation from the rendered view, but when I click on a suggestion, it still inputs the full name with the country at the end.

Is there an easy way to remove the country?

**Comment by sambokai** [comment]
Please use the discussion board for usage questions: https://gitter.im/react-places-autocomplete.

The following PR might help you: https://github.com/hibiken/react-places-autocomplete/pull/319

With this merged, you'll be able to access the raw `suggestion` object in the `onSelect` handler and from there use the `mainText` property. I.e. in the case of `Berlin, Germany`, `Berlin` is the `mainText`.
