### ISSUE TITLE
How to set restriction/option to query only selected type of places?

### ISSUE THREAD

**Issue by MeRahulAhire** [hibiken/react-places-autocomplete#312]
according to your [docs](https://github.com/hibiken/react-places-autocomplete#searchoptions), i tried to implement the code in my react app in the following way: 
```
import React, { Component } from 'react'
import './App.css'
import PlacesAutocomplete from "react-places-autocomplete";

export class App extends Component {
  constructor(props) {
    super(props);
    this.state = { address: '' };
  }
 
  handleChange = address => {
    this.setState({ address });
  };
  
  render() {
    const searchOptions = {
      types: ['university', 'school','college','secondary-school']
    }
    return (
      <div>
      <PlacesAutocomplete
      value={this.state.address}
      onChange={this.handleChange}
      onSelect={this.handleSelect}
      searchOptions={searchOptions}
      shouldFetchSuggestions={this.state.address.length > 2}
      
    >
      {({ getInputProps, suggestions, getSuggestionItemProps, loading }) => (
        <div >
          

          <input maxLength="50" className="typo"{...getInputProps({ placeholder: "Search Your College" })} />

          <div>
            {loading ? <div>...loading</div> : null}

            {suggestions.map(suggestion => {
              const style = {
                backgroundColor: suggestion.active ? "#41b6e6" : "",
              };
              return (
               
                <div className="suggestion"  {...getSuggestionItemProps(suggestion, { style })}>
                  {suggestion.description}
                </div>
               
              );
            })}
          </div>
        </div>
      )}
    </PlacesAutocomplete>
      </div>
    )
  }
}

export default App

```

to only get results from colleges, schools and university. But when i tried to add [this](https://github.com/hibiken/react-places-autocomplete#searchoptions):
```
render() {
    const searchOptions = {
      types: ['university', 'school','college','secondary-school']
    }
    return (
      <div>
      <PlacesAutocomplete
      value={this.state.address}
      onChange={this.handleChange}
      onSelect={this.handleSelect}
      searchOptions={searchOptions}
      shouldFetchSuggestions={this.state.address.length > 2}
      >
```
I wasn't able to get any suggestion after using `searchOption` before to that, it was working fine. 

Can you please tell me what I've done wrong and how can I improve it?

**Comment by sambokai** [comment]
Please use the discussion board for usage questions: https://gitter.im/react-places-autocomplete.

At a quick glance it seems as if you're using `searchOptions.types` wrongly.

From [the official docs on `AutocompletionRequest`](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest):

> The types of predictions to be returned. For a list of supported types, see the [developer's guide](https://developers.google.com/places/supported_types#table3). If nothing is specified, all types are returned. **In general only a single type is allowed.** The exception is that you can safely mix the 'geocode' and 'establishment' types, but note that this will have the same effect as specifying no types.

You can only restrict by one type except in the case of combining the types `geocode` and `establishment`.
