### ISSUE TITLE
See also: Material-UI Version

### ISSUE THREAD

**Issue by asktree** [hibiken/react-places-autocomplete#313]
Material-UI now provides an example of how to build this in their package. I prefer their version and wish I'd found it sooner. Consider linking to it in the README.

https://material-ui.com/components/autocomplete/#google-maps-place

Thanks for your version, though. It just doesn't seem to be maintained at this point and is a little tricky to incorporate with Gatsby.

**Comment by sambokai** [comment]
The documentation you've posted is implementing the data layer of autocomplete the way it's described or at least hinted at in the Google Maps API documentation. They then integrate it into their own view layer, using the material ui library. 

So the example is more of a general usage example of the Google Maps Autocomplete API. Documentation like that should be handled by the actual API docs and is out of scope of this project IMO.

This library is an **opinionated wrapper** around **both** the data layer and the view layer. 

The closest relative to this library is https://github.com/wellyshen/use-places-autocomplete, which is not concerned with the view layer but is a wrapper around the data part with an elegant API thanks to using the React hook pattern. I think referencing that library in our README makes more sense. 

It is fair to say, however, that active development and maintenance has been slow. We're working on that, by trying to find new maintainers and attending to open issues and PRs.
