### ISSUE TITLE
Can i restrict a countrie?

### ISSUE THREAD

**Issue by Amstrong** [hibiken/react-places-autocomplete#333]
I'm currently trying to get my autocomplete to restrict only one country. I have tried to find the form with the example but there is no documentation of this.

For this reason I would like to know if it is possible. Thank you.

**Comment by briansmith-fr** [comment]
Yes it is possible: For example, to return cities in Canada, 
```
          <PlacesAutocomplete
            value={this.state.address}
            onChange={this.handleChange}
            onSelect={this.handleSelect}
            searchOptions={{
              componentRestrictions: {
                country: ["ca"],
              },
              types: ["(cities)"],
            }}
          >
```
For USA, use ```...country: ["us"],...```

Regards,
Brian

**Comment by Amstrong** [comment]
Thank you very much Brian, it was very helpful for me.
