### ISSUE TITLE
No matter what value I pass to PlacesAutocomplete, it is undefined. React dev tools displays undefined for value

### ISSUE THREAD

**Issue by Ahmdrza** [hibiken/react-places-autocomplete#334]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

No matter what value I pass to PlacesAutocomplete, it is undefined in dev tools

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Pass any value to PlacesAutocomplete, it will give undefined in dev tools

**What is the expected behavior?**

the value should be whatever value is passed 

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

ReactPlacesAutocomplete: 7.2.1
browser: chrome 83.0.4103.116 (Official Build) (64-bit)
OS: windows 10 64 bit

**Comment by ganesh-papola** [comment]
any solution?
