### ISSUE TITLE
How to make address suggestion returned in a certain language? 

### ISSUE THREAD

**Issue by yingqi-chen** [hibiken/react-places-autocomplete#337]
Hi, so I notice that it will return the suggestions in the language consistent to my chrome browser settings. So I wonder is there a prop that I can send to <PlacesAutocomplete> to make sure the suggestions return in English so as to manage data easily? Thanks!
My autocomplete version is: 7.3.0

**Comment by brmk** [comment]
#291

**Comment by yingqi-chen** [comment]
@brmk thanks so much!
