### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by furyozo** [hibiken/react-places-autocomplete#345]
There is a key prop missing inside the PlacesAutocomplete component render method

![Capture](https://user-images.githubusercontent.com/20482304/96112879-9976d900-0ee3-11eb-964a-48320fa96d5c.PNG)

**Comment by OtavioPalma** [comment]
I had the same problem, the solution was to add a key prop inside the returned div of the map function, here's my code:
`<div>
   {loading && <Skeleton animation="wave" height={68} />}
   {suggestions.map(suggestion => {
      return (
         <div
            key={suggestion.placeId}
            {...getSuggestionItemProps(suggestion, {
               className: `${classes.modal_suggestions}`,
            })}>
               <span>{suggestion.formattedSuggestion.mainText}</span>
               <span>{suggestion.formattedSuggestion.secondaryText}</span>
         </div>);
             })}
 </div>`

**Comment by JulienMelissas** [comment]
Thanks for the tip @OtavioPalma - unfortunately I tried with both `suggestion.id` and `suggestion.placeId` and the error was still there. It's possible I tried something wrong though!

**Comment by OtavioPalma** [comment]
> Thanks for the tip @OtavioPalma - unfortunately I tried with both `suggestion.id` and `suggestion.placeId` and the error was still there. It's possible I tried something wrong though!

I was looking into the repo issues and I found this:
> ...just be sure that you add `key={suggestion.placeId}` _after_ the call to `getSuggestionItemProps()` or you'll over write the `key` with the `id` instead of the desired `placeId`.

Maybe that's what you're doing wrong?

**Comment by stesvis** [comment]
I also added `key={suggestion.placeId}` but the error still shows when you type the first character..
This worked tho, like @OtavioPalma said.
```
<div
  {...getSuggestionItemProps(suggestion, {
	className,
	style,
  })}
  key={suggestion.placeId}>
  <span>{suggestion.description}</span>
</div>
```

**Comment by OleksiiKachan** [comment]
had the same issue. was resolved after putting key prop to the very end. looks like getSuggestionItemProps overrides key prop

**Comment by simkieu** [comment]
I had the same issue. Took me a few days to look up on the internet and finally I found the answer here. Putting the key to the end solved the problem. Thanks all!

**Comment by krzysztofeko** [comment]
Thx man, on the end work: 
`<div 
  {...getSuggestionItemProps(suggestion, {
    className,
    style,
  })}
  key={suggestion.placeId}
>`
