### ISSUE TITLE
Restrict search suggestions to one country in my case Australia 

### ISSUE THREAD

**Issue by bpalmer661** [hibiken/react-places-autocomplete#355]
hibiken

Im trying to restrict search suggestions to one country in my case Australia 

what is the best way to do this now as I am struggling to work it out?

<PlacesAutocomplete
        fullWidth
        className="search-bar"
        value={address}
        onChange={setAddress}
        onSelect={handleSelect}
      >

**Comment by e-hop** [comment]
+1

**Comment by mrlaseptima** [comment]
I have the same issue . Why this issue is closed ?

**Comment by gavanitrate** [comment]
you need to use `searchOptions`
```
searchOptions={{
    componentRestrictions: { country: 'au' }
}}
```
