### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mikestecker** [hibiken/react-places-autocomplete#362]
**Do you want to request a *feature* or report a *bug*?**
**BUG**

**What is the current behavior?**
typing into the input, I get the following error:
```
Unhandled Runtime Error
TypeError: Cannot read property 'length' of undefined

Call Stack
PlacesAutocomplete._this.fetchPredictions
node_modules/react-places-autocomplete/dist/PlacesAutocomplete.js (101:0)
```

**What is the expected behavior?**
type into input without getting error

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
`"react-places-autocomplete": "^7.3.0"`
`"react": "17.0.2"`
`"next": "10.1.3"`

**Comment by Jazzykhan** [comment]
did you solved it?
