### ISSUE TITLE
Issue in setState :- Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setState')

### ISSUE THREAD

**Issue by Raghu-M-S** [hibiken/react-places-autocomplete#385]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**

**Comment by Raghu-M-S** [comment]
issue

**Comment by Raghu-M-S** [comment]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setState')

**Comment by Paul-Taiwo** [comment]
If you are still facing this bug. Please kindly create a new issue with steps to reproduce the bug.
