### ISSUE TITLE
Language option is not working

### ISSUE THREAD

**Issue by damdafayton** [hibiken/react-places-autocomplete#391]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
<PlacesAutocomplete searchOptions={{ language='any language' }}>
</PlacesAutocomplete>
```

doesnt return the response in the selected language.

**What is the expected behavior?**
` searchOptions={{ language='de' }}`
should return response in German.

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
`7.3.0`

**Comment by Paul-Taiwo** [comment]
Change `"="` to `":"` `searchOptions={{ language: 'de' }}`

Are you using the right language code. [Check here](https://developers.google.com/maps/faq?authuser=1#languagesupport) for Supported Languages


German
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33280888/211725886-6681509c-e69d-4995-8799-7f9d0eec5114.png">

English
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33280888/211726082-d36c7598-1d70-468b-bd84-a265974cd6bd.png">
