### ISSUE TITLE
Server returned status code ZERO_RESULTS

### ISSUE THREAD

**Issue by brilianrn** [hibiken/react-places-autocomplete#393]
_**Do you want to request a *feature* or report a *bug*?**_
Bug Issue

_**What is the current behavior?**_
Currently still in the process of finding a solution to the bug that occurred

_**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**_
In a project, I'm working on I installed code from react-places-autocomplete to perform a location search with keywords entered by the user. 

Everything works normally, but when I search with the keyword "Arcadia Daanmogot" and choose the first option from the suggestions, I get an error "Server returned status code ZERO_RESULTS".

I got the error in the code line like this:
`geocodeByAddress(address)
      .then((results) => {
        console.log(results, ' ====== RESULT')
        // getLatLng(results[0])
      })
     .catch(err => console.log(err, ' ERROR'))`

I got the error when I run `geocodeByAddress` with the keyword _"Arcadia Daanmogot"_ and choose the first option from the suggestions.

_**What is the expected behavior?**_
Doing a normal search and getting a location that matches what the user wants.

_**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**_
For react-places-autocomplete, I used version 7.3.0. And for browser/OS are affected by this issue is all of browser/OS.

Please help my issue @hibiken

**Comment by Paul-Taiwo** [comment]
I tried replicating the bug but it seems to work fine.
If the bug still persists please raise another issue.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33280888/211727350-aa077ffa-d533-4f69-9209-5841e6e183fb.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33280888/211727447-690ea17c-a652-4788-9043-16f7483ca8c0.png">

**Comment by SyedMuttaqeenRizvi** [comment]
Hi i been using this LIb for 3 years now and now suddenly i started having the same issue when i do a specific search 
"Paris Charles de Gaulle Airport (CDG), Roissy-en-France, France".
This gives me 0 results same as mentioned above and is causing alot to business. If someone can help me on this would be great.
