### ISSUE TITLE
parse address using fillInAddress

### ISSUE THREAD

**Issue by JohnnyKNL** [hibiken/react-places-autocomplete#50]
Thanks for the repo. I'm using it now but want to be able to split the address into separate fields. Google has the fillInAddress function but I'm too new at this to incorporate it. Here is a stackoverflow with the same issue in another set of code: http://stackoverflow.com/questions/42350100/google-places-autocomplete-react-component
Thanks!

**Comment by MaxGabriel** [comment]
@JohnnyKNL or @nathanmathis did you ever figure out a way to do this (get the individual address components, not just the full address)? I wanted to have the first field be an autocomplete field, and if you selected an address the region, country, postal code, etc. would be filled in automatically (similar to [Google's example](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)). But I think this library only supports getting the full address and wondered if you found a better solution.

**Comment by denisftw** [comment]
@JohnnyKNL @MaxGabriel It's not about the library - it's about API the library is using. If you use `google.maps.places.Autocomplete`, then the returning object will contain address components but Google will also attach the suggestion box to the input. This library, however, uses `google.maps.places.AutocompleteService`. It doesn't attach anything, but doesn't return individual parts either.

**Comment by MaxGabriel** [comment]
Thanks @denisftw! I came to the same conclusion. Really confuses me why Google made that API choice in one spot but not another

**Comment by denisftw** [comment]
@MaxGabriel Yeah, it makes no sense. By the way, did you find how to get address information from `place_id` once you got it from suggestions?

**Comment by MaxGabriel** [comment]
Yes I did. Sorry for the poor formatting, I’m in my phone on a ski trip. Also note that it’s in Typescript:

```
const div = document.createElement('div')
              const service = new google.maps.places.PlacesService(div)
              service.getDetails({placeId: placeId}, (results, status) => {
                if (status === google.maps.places.PlacesServiceStatus.OK) {
                  resolve(results)
                } else {
                  reject(status)
                }
              })
```

**Comment by denisftw** [comment]
Awesome, thanks! I looked at `PlacesService`, but didn't like that it wanted a map as an argument. Using an empty div is definitely a good idea.

**Comment by CoVoCre** [comment]
Hey @JohnnyKNL , couldn't it be possible by having for example the input field you provide to react-places-autocomplete hidden, and having multiple inputs visible to the user. You can then, every time the user inputs something in the visible inputs, change / concatenate what the hidden input of react-places-autocomplete is getting ? Otherwise from react-places-autocomplete we could maybe add a boolean flag like noInputNeeded, which would not add any input. But then we'd need to tell react-places-autocomplete when it has "focus" and start fetching... It'd make it completely stateless though, and that'd be good 😊

**Comment by sambokai** [comment]
Closing this in an effort to clean up the repo. Please let us know if you think that this should be re-opened. https://github.com/hibiken/react-places-autocomplete/issues/325
