### ISSUE TITLE
Is it possible to bind API key via runtime env variable?

### ISSUE THREAD

**Issue by heymartinadams** [hibiken/react-places-autocomplete#90]
Currently, you have to insert JS in main html file, like this:
`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=___API_KEY___&libraries=places"></script>`

Would it be possible, perhaps in a future version, to add the API key & Google Places API inside the code, like this? That way the API key remains hidden in production.
`geocodeByAddress.key(process.env.REACT_APP_GOOGLE_API_KEY)`

Thank you  🙏🏽

**Comment by TryingToImprove** [comment]
This seems like a issue which #57 will solve?

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
