### ISSUE TITLE
Debounce cancellation on Enter Key

### ISSUE THREAD

**Issue by Artur-A** [hibiken/react-places-autocomplete#94]
Hi,

Our users find inconvenient to use Enter Key with auto complete in a fast manner.

1. Open https://kenny-hibino.github.io/react-places-autocomplete/
2. Paste 'New York, NY, United States' text in the input field and _immediately_ press Enter key.
3. In 1-2 seconds the popup list with suggestions will be opened. If some presses Enter key second time the popup will be closed.

This is annoying when a user knows the exact address and wants confidently press 'Enter' key without any popup for further actions.

The problem occurs due the debounce behaviour:
a) Text paste leads to a text change, which calls fetching suggestions from google service in 200 ms.
b) 'Enter' key calls 'clear autocomplete'.
c) Debounce and fetch returns 'autocompleteFallback' and shows popup with suggestions ignoring 'clear autocomplete'.

See a small fix https://github.com/Artur-A/react-places-autocomplete/commit/126abdadf01d452630a30ed07e68045b3aef2a5e

Should we merge it or will this behaviour break something?

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
