### ISSUE TITLE
Callback is Not Defined

### ISSUE THREAD

**Issue by Tenkir** [hibiken/react-places-autocomplete#96]
**Issue:**
geocodeByAddress does not work with promises as documentation states. Must be passed a callback.

**Error:**
`utils.js:21 Uncaught TypeError: callback is not a function`

**Version:**
v5.3.1

**Code:**
```
handleSelect = (address) => {
  geocodeByAddress(address)
   .then((results) => console.log(results))
   .catch((error) => {
     console.log('Oh no!', error)
   })
}
```

**Comment by kenny-hibino** [comment]
@Tenkir Thanks for reporting! I will take a look at this issue this week 👍

**Comment by sambokai** [comment]
Closing this issue/PR in an effort to clean up the repo. Please let us know if you think that it should be re-opened. #325
